//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DauevaApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public long id { get; set; }
        public string Message { get; set; }
        public long Master_id { get; set; }
        public long Request_id { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Users Master { get; set; }
    }
}
